index:
    path: /
    controller: App\Controller\DefaultController::index

accueil:
    path: /accueil
    controller: App\Controller\DefaultController::accueil

formation:
    path: /formation
    controller: App\Controller\DefaultController::formation

materiel:
    path: /materiel
    controller: App\Controller\DefaultController::materiel

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact