index:
    path: /
    controller: App\Controller\DefaultController::index

accueil:
    path: /accueil
    controller: App\Controller\DefaultController::accueil

formations:
    path: /formations
    controller: App\Controller\FormationController::index

formation_voiture:
    path: /formation/voiture
    controller: App\Controller\FormationController::formation_voiture

formation_moto:
    path: /formation/moto
    controller: App\Controller\FormationController::formation_moto

formation_poid_lourd:
    path: /formation/poid-lourd
    controller: App\Controller\FormationController::formation_poid_lourd

formation_remorque:
    path: /formation/remorque
    controller: App\Controller\FormationController::formation_remorque

materiel:
    path: /materiel
    controller: App\Controller\MaterielController::materiel

contact:
    path: /contact
    controller: App\Controller\ContactController::contact