index:
    path: /
    controller: App\Controller\DefaultController::index

accueil:
    path: /accueil
    controller: App\Controller\DefaultController::accueil
formation_voiture:
    path: /formation/voiture
    controller: App\Controller\FormationController::formation_voiture

formation_deux_roues:
    path: /formation/deux-roues
    controller: App\Controller\FormationController::formation_deux_roues

formation_poid_lourd:
    path: /formation/poid-lourd
    controller: App\Controller\FormationController::formation_poid_lourd

formation_remorque:
    path: /formation/remorque
    controller: App\Controller\FormationController::formation_remorque

materiel:
    path: /materiel
    controller: App\Controller\MaterielController::materiel

label:
    path: /label
    controller: App\Controller\LabelController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::contact